export const products = [
  {
    'id': 1,
    'type': 'top',
    'brand': 'alo yoga',
    'name': 'Airwave T',
    'size': {'neck': 15, 'chest': 38},
    'picture': '1_simple_tee.png',
    'style': ['simple'],
    'price': 200,
  },
  {
    'id': 2,
    'type': 'top',
    'brand': 'ck',
    'name': 'White top',
    'size': {'chest': 38},
    'picture': '2_ck_white_top.png',
    'style': ['elegant'],
    'price': 360,
  },
  {
    'id': 3,
    'type': 'top ',
    'brand': 'dolce & gabbana',
    'name': 'Elegant blue',
    'size': {'chest': 38},
    'picture': '3_elegant_blue.png',
    'style': ['elegant', 'bold'],
    'price': 1200,
  },
  {
    'id': 4,
    'type': 'bottom',
    'brand': 'alo yoga',
    'name': 'Regenerate Short in Black',
    'size': {'waist ': 33},
    'picture': '4_alo_yoga_pants.png',
    'style': ['simple'],
    'price': 240,
  },
  {
    'id': 5,
    'type': 'bottom',
    'brand': 'versace',
    'name': 'Versace jeans',
    'size': {'waist': 33},
    'picture': '5_versace_jeans.png',
    'style': ['simple'],
    'price': 270,
  },
  {
    'id': 6,
    'type': 'bottom',
    'brand': 'rag & bone',
    'name': 'Alex`s skirt',
    'size': {'waist': 34, 'hip': 42, 'thigh': 24, 'knee': 16, 'bottom': 14, 'front_rise': 11, 'high_rise': 14},
    'picture': '6_Rag & Bone alex jeans.png',
    'style': ['simple'],
    'price': 1900,
  }
]
